app:
  image: nginx:1.10
  volumes:
    - ./app:/usr/share/nginx/html
hub:
  image: selenium/hub:2.53.0
chrome:
  image: selenium/node-chrome:2.53.0
  links:
    - hub
    - app
firefox:
  image: selenium/node-firefox:2.53.0
  links:
    - hub
    - app
chromedebug:
  image: selenium/node-chrome-debug:2.53.0
  links:
    - hub
    - app
  ports:
    - 5900:5900
firefoxdebug:
  image: selenium/node-firefox-debug:2.53.0
  links:
    - hub
    - app
  ports:
    - 5901:5900
nightwatch:
  image: meticulo3366/node:4.2.2-utils
  working_dir: /home/node
  links:
    - hub
  volumes:
    - ./test:/home/node
  command: bash -c "sleep 20 && nightwatch -t spec.js"
